Planning/Areas/Admin/Models/OrganizationSetupViewModel/OrganizationSetupViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Planning.Areas.Admin.Models.OrganizationSetupViewModel
{
    public class OrganizationSetupViewModel
    {
        public int Organization_Setup_Id { get; set; }
        public string Organization_Name { get; set; }
        public string Organization_Type { get; set; }
        public string District_Name { get; set; }
        public string State_Country { get; set; }
        public string Image_Path { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public List<OrganizationSetupViewModel> OrganizationSetupViewModelList { get; set; }


        public int Kar_Katti_Id { get; set; }
        public string Contigency { get; set; }
        public string SamajikSurekchya { get; set; }
        public string BahalKar { get; set; }
        public string AgrimShulka { get; set; }
        public string Parishramik { get; set; }
        public string MarmatSambhar { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public List<OrganizationSetupViewModel> KarKattiViewModelList { get; set; }

        public int Sarta_Setup_Id { get; set; }
        public string Description { get; set; }
        public List<OrganizationSetupViewModel> SartaViewModelList { get; set; }

    }
}

Planning/Areas/Admin/Controllers/OrganizationSetupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Planning.Areas.Admin.Models.OrganizationSetupViewModel;
using Planning.Planning.Entities;
using System.Data;
using System.IO;

namespace Planning.Areas.Admin.Controllers
{
    [Authorize]
    public class OrganizationSetupController : Controller
    {
        PLANNING_OCT_03Entities ent = new PLANNING_OCT_03Entities();

        public object EntityState { get; private set; }

        public ActionResult Index()
        {
            OrganizationSetupViewModel model = new OrganizationSetupViewModel();
            model.OrganizationSetupViewModelList = (from i in ent.Organization_Setup
                                                    select new OrganizationSetupViewModel
                                                    {
                                                        Organization_Setup_Id=i.Organization_Setup_Id,
                                                        Organization_Name = i.Organization_Name,
                                                        Organization_Type=i.Organization_Type,
                                                        District_Name = i.District_Name,
                                                        State_Country = i.State_Country,
                                                        Image_Path=i.Image_Path,
                                                    }).ToList();
            return View(model);
        }

        public ActionResult Create()
        {
            OrganizationSetupViewModel model = new OrganizationSetupViewModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(OrganizationSetupViewModel model,HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                var imagePath = "/Documents/";
                if (file != null)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath(imagePath), fileName);
                    file.SaveAs(path);
                    model.Image_Path = imagePath + file.FileName;
                }
                try
                {
                    var Organization_SetupEntity = new Organization_Setup()
                    {
                        Organization_Name = model.Organization_Name,
                        Organization_Type = model.Organization_Type,
                        District_Name = model.District_Name,
                        State_Country = model.State_Country,
                        Image_Path=model.Image_Path,
                        CreatedBy = model.CreatedBy,
                        CreatedDate = DateTime.Now,
                    };
                    ent.Organization_Setup.Add(Organization_SetupEntity);
                    ent.SaveChanges();
                }
                catch (Exception e)
                {
                }
            }
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            OrganizationSetupViewModel model = new OrganizationSetupViewModel();
            var data = ent.Organization_Setup.Where(x => x.Organization_Setup_Id == id).SingleOrDefault();
            model.Organization_Setup_Id = data.Organization_Setup_Id;
            model.Organization_Name = data.Organization_Name;
            model.Organization_Type = data.Organization_Type;
            model.District_Name = data.District_Name;
            model.State_Country = data.State_Country;
            model.Image_Path = data.Image_Path;
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(OrganizationSetupViewModel model, HttpPostedFileBase file)
        {
            var imagePath = "/Documents/";
            if (file != null)
            {
                var fileName = Path.GetFileName(file.FileName);
                var path = Path.Combine(Server.MapPath(imagePath), fileName);
                file.SaveAs(path);
                model.Image_Path = imagePath + file.FileName;
            }

            var data = ent.Organization_Setup.Where(x => x.Organization_Setup_Id == model.Organization_Setup_Id).SingleOrDefault();
            data.Organization_Setup_Id = model.Organization_Setup_Id;
            data.Organization_Name = model.Organization_Name;
            data.Organization_Type = model.Organization_Type;
            data.District_Name = model.District_Name;
            data.State_Country = model.State_Country;
            if(model.Image_Path==null)
            {
                data.Image_Path = data.Image_Path;
            }
            else
            {
                data.Image_Path = model.Image_Path;
            }
            ent.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

Planning/Areas/Admin/Views/OrganizationSetup/Create.cshtml
@model Planning.Areas.Admin.Models.OrganizationSetupViewModel.OrganizationSetupViewModel

@{
    ViewBag.Title = "";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}



<div class="padding-md">
    @if (TempData["alreadyexist"] != null)
    {
        <div class="alert alert-info">
            <h5 style="text-align:center"><strong style="color:red;">@TempData["alreadyexist"]</strong></h5>
        </div>
    }

    <section style="background:#efefe9;">
        <div class="container">
            <div class="row">
                <div class="board">
                    <div class="tab-content">
                        <div class="tab-pane fade in active" id="fiscalYearRecord">
                            <h3 class="step_ttl">राख्नुहोस </h3>
                            @using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data", @class = "well", @id = "contact_form" }))
                            {
                                @Html.ValidationSummary()
                                <fieldset>
                                    <div class="row">
                                        <div class="col-lg-4 col-md-6">
                                            <div class="form-group">
                                               <label>नाम</label>
                                                @Html.EditorFor(model => model.Organization_Name, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Organization_Name, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-6">
                                            <div class="form-group">
                                                <label>कार्यालय</label>
                                                @Html.EditorFor(model => model.Organization_Type, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Organization_Type, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-6">
                                            <div class="form-group">
                                                <label>ठेगाना</label>
                                                @Html.EditorFor(model => model.District_Name, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.District_Name, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-6">
                                            <div class="form-group">
                                                <label>प्रदेश</label>
                                                @Html.EditorFor(model => model.State_Country, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.State_Country, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-6">
                                            <div class="form-group">
                                                <label>कार्यालय लोगो</label>
                                                <input type="file" name="file" />
                                            </div>
                                        </div>
                                    </div>
                                    <div class="clearfix"></div>
                                    <p>&nbsp;</p>
                                    <div class="form-group">
                                        <label class="col-lg-3  col-md-4 control-label"></label>
                                        <div class="col-lg-7 col-md-7">
                                            <button type="submit" class="btn btn-success">सुरक्षित गर्नुहोस </button>
                                            @Html.ActionLink("मुख्य मेनु", "Index", null, new { @class = "btn btn-info" })
                                        </div>
                                    </div>
                                </fieldset>
                            }
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
    </section>

</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Planning/Areas/Admin/Views/OrganizationSetup/Edit.cshtml
@model Planning.Areas.Admin.Models.OrganizationSetupViewModel.OrganizationSetupViewModel

@{
    ViewBag.Title = "";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}



<div class="padding-md">
    @if (TempData["alreadyexist"] != null)
    {
        <div class="alert alert-info">
            <h5 style="text-align:center"><strong style="color:red;">@TempData["alreadyexist"]</strong></h5>
        </div>
    }

    <section style="background:#efefe9;">
        <div class="container">
            <div class="row">
                <div class="board">
                    <div class="tab-content">
                        <div class="tab-pane fade in active" id="fiscalYearRecord">
                            <h3 class="step_ttl">राख्नुहोस् </h3>
                            @using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data", @class = "well", @id = "contact_form" }))
                            {
                                @Html.ValidationSummary()
                                @Html.HiddenFor(model=>model.Organization_Setup_Id)
                                <fieldset>
                                    <div class="row">
                                        <div class="col-lg-4 col-md-6">
                                            <div class="form-group">
                                                <label>नाम</label>
                                                @Html.EditorFor(model => model.Organization_Name, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Organization_Name, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-6">
                                            <div class="form-group">
                                                <label>कार्यालय</label>
                                                @Html.EditorFor(model => model.Organization_Type, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Organization_Type, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-6">
                                            <div class="form-group">
                                                <label>ठेगाना</label>
                                                @Html.EditorFor(model => model.District_Name, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.District_Name, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-6">
                                            <div class="form-group">
                                                <label>प्रदेश</label>
                                                @Html.EditorFor(model => model.State_Country, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.State_Country, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-6">
                                            <div class="form-group">
                                                <label>कार्यालय लोगो</label>
                                                <input type="file" name="file" />
                                            </div>
                                        </div>
                                    </div>
                                    <div class="clearfix"></div>
                                    <p>&nbsp;</p>
                                    <div class="form-group">
                                        <label class="col-lg-3  col-md-4 control-label"></label>
                                        <div class="col-lg-7 col-md-7">
                                            <button type="submit" class="btn btn-success">सुरक्षित गर्नुहोस </button>
                                            @Html.ActionLink("मुख्य मेनु", "Index", null, new { @class = "btn btn-info" })
                                        </div>
                                    </div>
                                </fieldset>
                            }
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
    </section>

</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Planning/Areas/Admin/Views/OrganizationSetup/Index.cshtml
@model Planning.Areas.Admin.Models.OrganizationSetupViewModel.OrganizationSetupViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    int i = 1;

    List<Planning.Planning.Entities.Organization_Setup> OrganiationName = new List<Planning.Planning.Entities.Organization_Setup>();
    using (Planning.Planning.Entities.PLANNING_OCT_03Entities db = new Planning.Planning.Entities.PLANNING_OCT_03Entities())
    {
        OrganiationName = (from j in db.Organization_Setup select j).ToList();
    }

}


<div class="padding-md">
   
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="panel panel-default">
                <div class="header-list" style="text-align: center">
                    <h2> नगरपालिका</h2>
                </div>
                <hr />

                @if (OrganiationName.Count() > 0)
                {
                    <div class="panel-heading">
                    </div>
                }
                else
                {
                    <div class="panel-heading">
                        @Html.ActionLink("नयाँ राख्नुहोस्", "Create", null, new { @class = "btn btn-success btn_add btn-xs" })
                    </div>
                }
                
                <table class="table table-bordered table-condensed table-hover table-striped">
                    <thead>
                        <tr class="success">
                            <th>क्र.स.</th>
                            <th>नाम</th>
                            <th>कार्यालय</th>
                            <th>ठेगाना</th>
                            <th>प्रदेश</th>
                            <th>कार्यालय लोगो</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.OrganizationSetupViewModelList)
                        {
                            <tr>
                                <th>@Planning.Utility.NepaliEnglishNumber.English_Nepali(i.ToString())</th>
                                <td>@Html.DisplayFor(modelItem => item.Organization_Name)</td>
                                <td>@Html.DisplayFor(modelItem => item.Organization_Type)</td>
                                <td>@Html.DisplayFor(modelItem => item.District_Name)</td>
                                <td>@Html.DisplayFor(modelItem => item.State_Country)</td>
                                <td><img src="@item.Image_Path" height="80" width="80"/></td>
                                <td>
                                    <a class="btn btn-success btn-sm" title="Edit" href="@Url.Action("Edit", "OrganizationSetup", new { id = item.Organization_Setup_Id })"><i class="fa fa-edit"></i> सच्याउनुहोस्</a>
                                </td>
                            </tr>
                            i++;
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>