Planning/Areas/Admin/Controllers/KarKattiSetupController/KarKattiSetupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Planning.Areas.Admin.Models.OrganizationSetupViewModel;
using Planning.Planning.Entities;
using System.Data;

namespace Planning.Areas.Admin.Controllers.KarKattiSetupController
{
    [Authorize]
    public class KarKattiSetupController : Controller
    {
        PLANNING_OCT_03Entities ent = new PLANNING_OCT_03Entities();
        public ActionResult Index()
        {
            OrganizationSetupViewModel model = new OrganizationSetupViewModel();
            model.KarKattiViewModelList = (from i in ent.Kar_Katti
                                           select new OrganizationSetupViewModel
                                           {
                                               Kar_Katti_Id = i.Kar_Katti_Id,
                                               Contigency = i.Contigency,
                                               SamajikSurekchya = i.SamajikSurekchya,
                                               BahalKar = i.BahalKar,
                                               AgrimShulka = i.AgrimShulka,
                                               Parishramik = i.Parishramik,
                                               MarmatSambhar=i.MarmatSambhar,
                                           }).ToList();
            return View(model);
        }

        public ActionResult Create()
        {
            OrganizationSetupViewModel model = new OrganizationSetupViewModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(OrganizationSetupViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var Kar_KattiEntity = new Kar_Katti()
                    {
                        Contigency = model.Contigency,
                        SamajikSurekchya = model.SamajikSurekchya,
                        BahalKar = model.BahalKar,
                        AgrimShulka = model.AgrimShulka,
                        Parishramik = model.Parishramik,
                        MarmatSambhar=model.MarmatSambhar,
                        Status=true,
                        CreatedBy = model.CreatedBy,
                        CreatedDate = DateTime.Now,
                    };
                    ent.Kar_Katti.Add(Kar_KattiEntity);
                    ent.SaveChanges();
                }
                catch (Exception e)
                {
                }
            }
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            OrganizationSetupViewModel model = new OrganizationSetupViewModel();
            var data = ent.Kar_Katti.Where(x => x.Kar_Katti_Id == id).SingleOrDefault();
            model.Kar_Katti_Id = data.Kar_Katti_Id;
            model.Contigency = data.Contigency;
            model.SamajikSurekchya = data.SamajikSurekchya;
            model.BahalKar = data.BahalKar;
            model.AgrimShulka = data.AgrimShulka;
            model.Parishramik = data.Parishramik;
            model.MarmatSambhar = data.MarmatSambhar;
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(OrganizationSetupViewModel model)
        {
            var data = ent.Kar_Katti.Where(x => x.Kar_Katti_Id == model.Kar_Katti_Id).SingleOrDefault();
            data.Kar_Katti_Id = model.Kar_Katti_Id;
            data.Contigency = model.Contigency;
            data.SamajikSurekchya = model.SamajikSurekchya;
            data.BahalKar = model.BahalKar;
            data.AgrimShulka = model.AgrimShulka;
            data.Parishramik = model.Parishramik;
            data.MarmatSambhar = model.MarmatSambhar;
            data.Status = true;
            data.UpdatedBy = model.UpdatedBy;
            data.UpdatedDate = DateTime.Now;
            ent.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Planning/Areas/Admin/Views/KarKattiSetup/Create.cshtml
@model Planning.Areas.Admin.Models.OrganizationSetupViewModel.OrganizationSetupViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}



<div class="padding-md">
    @if (TempData["alreadyexist"] != null)
    {
        <div class="alert alert-info">
            <h5 style="text-align:center"><strong style="color:red;">@TempData["alreadyexist"]</strong></h5>
        </div>
    }

    <section style="background:#efefe9;">
        <div class="container">
            <div class="row">
                <div class="board">
                    <div class="tab-content">
                        <div class="tab-pane fade in active" id="fiscalYearRecord">
                            <h3 class="step_ttl">राख्नुहोस </h3>
                            @using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data", @class = "well", @id = "contact_form" }))
                            {
                                @Html.ValidationSummary()
                                <fieldset>
                                    <div class="row">
                                        <div class="col-lg-4 col-md-6">
                                            <div class="form-group">
                                                <label>कन्टेन्जेन्सी( प्रतिशतमा)</label>
                                                @Html.EditorFor(model => model.Contigency, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Contigency, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-6">
                                            <div class="form-group">
                                                <label>मर्मत सम्भार( प्रतिशतमा)</label>
                                                @Html.EditorFor(model => model.MarmatSambhar, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.MarmatSambhar, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-6">
                                            <div class="form-group">
                                                <label>सामाजिक सुरक्षा कर( प्रतिशतमा)</label>
                                                @Html.EditorFor(model => model.SamajikSurekchya, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.SamajikSurekchya, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-6">
                                            <div class="form-group">
                                                <label>अग्रिम आय कर( प्रतिशतमा)</label>
                                                @Html.EditorFor(model => model.AgrimShulka, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.AgrimShulka, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-6">
                                            <div class="form-group">
                                                <label>पारिश्रमिक कर( प्रतिशतमा)</label>
                                                @Html.EditorFor(model => model.Parishramik, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Parishramik, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-6">
                                            <div class="form-group">
                                                <label>बहाल कर( प्रतिशतमा)</label>
                                                @Html.EditorFor(model => model.BahalKar, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.BahalKar, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="clearfix"></div>
                                    <p>&nbsp;</p>
                                    <div class="form-group">
                                        <label class="col-lg-3  col-md-4 control-label"></label>
                                        <div class="col-lg-7 col-md-7">
                                            <button type="submit" class="btn btn-success">सुरक्षित गर्नुहोस </button>
                                            @Html.ActionLink("मुख्य मेनु", "Index", null, new { @class = "btn btn-info" })
                                        </div>
                                    </div>
                                </fieldset>
                            }
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
    </section>

</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Planning/Areas/Admin/Views/KarKattiSetup/Edit.cshtml
@model Planning.Areas.Admin.Models.OrganizationSetupViewModel.OrganizationSetupViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}



<div class="padding-md">
    @if (TempData["alreadyexist"] != null)
    {
        <div class="alert alert-info">
            <h5 style="text-align:center"><strong style="color:red;">@TempData["alreadyexist"]</strong></h5>
        </div>
    }

    <section style="background:#efefe9;">
        <div class="container">
            <div class="row">
                <div class="board">
                    <div class="tab-content">
                        <div class="tab-pane fade in active" id="fiscalYearRecord">
                            <h3 class="step_ttl">राख्नुहोस </h3>
                            @using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data", @class = "well", @id = "contact_form" }))
                            {
                                @Html.ValidationSummary()
                                @Html.HiddenFor(model=>model.Kar_Katti_Id)
                                <fieldset>
                                    <div class="row">
                                        <div class="col-lg-4 col-md-6">
                                            <div class="form-group">
                                                <label>कन्टेन्जेन्सी( प्रतिशतमा)</label>
                                                @Html.EditorFor(model => model.Contigency, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Contigency, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-6">
                                            <div class="form-group">
                                                <label>मर्मत सम्भार( प्रतिशतमा)</label>
                                                @Html.EditorFor(model => model.MarmatSambhar, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.MarmatSambhar, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-6">
                                            <div class="form-group">
                                                <label>सामाजिक सुरक्षा कर( प्रतिशतमा)</label>
                                                @Html.EditorFor(model => model.SamajikSurekchya, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.SamajikSurekchya, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-6">
                                            <div class="form-group">
                                                <label>अग्रिम आय कर( प्रतिशतमा)</label>
                                                @Html.EditorFor(model => model.AgrimShulka, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.AgrimShulka, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-6">
                                            <div class="form-group">
                                                <label>पारिश्रमिक कर( प्रतिशतमा)</label>
                                                @Html.EditorFor(model => model.Parishramik, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Parishramik, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-6">
                                            <div class="form-group">
                                                <label>बहाल कर( प्रतिशतमा)</label>
                                                @Html.EditorFor(model => model.BahalKar, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.BahalKar, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="clearfix"></div>
                                    <p>&nbsp;</p>
                                    <div class="form-group">
                                        <label class="col-lg-3  col-md-4 control-label"></label>
                                        <div class="col-lg-7 col-md-7">
                                            <button type="submit" class="btn btn-success">सुरक्षित गर्नुहोस </button>
                                            @Html.ActionLink("मुख्य मेनु", "Index", null, new { @class = "btn btn-info" })
                                        </div>
                                    </div>
                                </fieldset>
                            }
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
    </section>

</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Planning/Areas/Admin/Views/KarKattiSetup/Index.cshtml
@model Planning.Areas.Admin.Models.OrganizationSetupViewModel.OrganizationSetupViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    int i = 1;

    List<Planning.Planning.Entities.Kar_Katti> KarKatti = new List<Planning.Planning.Entities.Kar_Katti>();
    using (Planning.Planning.Entities.PLANNING_OCT_03Entities db = new Planning.Planning.Entities.PLANNING_OCT_03Entities())
    {
        KarKatti = (from j in db.Kar_Katti select j).ToList();
    }

}


<div class="padding-md">

    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="panel panel-default">
                <div class="header-list" style="text-align: center">
                    <h2> कर कट्टी</h2>
                </div>
                <hr />

                @if (KarKatti.Count() > 0)
                {
                    <div class="panel-heading">
                    </div>
                }
                else
                {
                    <div class="panel-heading">
                        @Html.ActionLink("नयाँ राख्नुहोस्", "Create", null, new { @class = "btn btn-success btn_add btn-xs" })
                    </div>
                }

                <table class="table table-bordered table-condensed table-hover table-striped">
                    <thead>
                        <tr class="success">
                            <th>क्र.स.</th>
                            <th>कन्टेन्जेन्सी</th>
                            <th>मर्मत सम्भार</th>
                            <th>सामाजिक सुरक्षा कर</th>
                            <th>अग्रिम आय कर</th>
                            <th>पारिश्रमिक कर </th>
                            <th>बहाल कर </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.KarKattiViewModelList)
                        {
                            <tr>
                                <th>@Planning.Utility.NepaliEnglishNumber.English_Nepali(i.ToString())</th>
                                <td>@Html.DisplayFor(modelItem => item.Contigency)</td>
                                <td>@Html.DisplayFor(modelItem => item.MarmatSambhar)</td>
                                <td>@Html.DisplayFor(modelItem => item.SamajikSurekchya)</td>
                                <td>@Html.DisplayFor(modelItem => item.AgrimShulka)</td>
                                <td>@Html.DisplayFor(modelItem => item.Parishramik)</td>
                                <td>@Html.DisplayFor(modelItem => item.BahalKar)</td>
                                <td>
                                    <a class="btn btn-success btn-sm" title="Edit" href="@Url.Action("Edit", "KarKattiSetup", new { id = item.Kar_Katti_Id })"><i class="fa fa-edit"></i> सच्याउनुहोस्</a>
                                </td>
                            </tr>
                            i++;
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>