Planning/Areas/Admin/Models/FiscalYearRecordViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Planning.Areas.Admin.Models
{
    public class FiscalYearRecordViewModel
    {
        public int Fiscal_Year_Record_Id { get; set; }
        [Required(ErrorMessage = "क्रिपया आर्थिक वर्ष राखनुहोस ।")]
        public string Title { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public List<FiscalYearRecordViewModel> FiscalYearRecordViewModelList { get; set; }

    }
}

Planning/Areas/Admin/Controllers/FiscalYearRecordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Planning.Areas.Admin.Models;
using Planning.Planning.Entities;
using System.Data;
using Newtonsoft.Json.Linq;

namespace Planning.Areas.Admin.Controllers
{
    [Authorize]
    public class FiscalYearRecordController : Controller
    {
        PLANNING_OCT_03Entities ent = new PLANNING_OCT_03Entities();
        public ActionResult Index()
        {
            FiscalYearRecordViewModel model = new FiscalYearRecordViewModel();
            model.FiscalYearRecordViewModelList = (from i in ent.Fiscal_Year_Record
                                                    select new FiscalYearRecordViewModel
                                                    {
                                                        Fiscal_Year_Record_Id = i.Fiscal_Year_Record_Id,
                                                        Title = i.Title,
                                                        IsActive = i.IsActive??false,
                                                    }).ToList();

            return View(model.FiscalYearRecordViewModelList);
        }

        ////test
        //public JsonResult fiscalYearAllRecords()
        //{
        //    var list = ent.Fiscal_Year_Record.Select(x => new FiscalYearRecordViewModel()
        //    {
        //        Fiscal_Year_Record_Id = x.Fiscal_Year_Record_Id,
        //        Title = x.Title,
        //        IsActive = x.IsActive ?? false
        //    }).ToList();
        //    return Json(new { data = list }, JsonRequestBehavior.AllowGet);
        //}

        [HttpPost]
        public ActionResult EditTableData(int id, string propertyName, string value)
        {
            var status = false;
            var message = "";
            object updateValue = value;
            //Update data to database 
            using (var con = new PLANNING_OCT_03Entities())
            {
                var records = con.Fiscal_Year_Record.Find(id);
                
                bool isValid = true;

                if (propertyName == "IsActive")
                {
                    int status1 = Convert.ToInt16(value);
                    if (status1 == 1)
                    {
                        var activeList = con.Fiscal_Year_Record.Where(x => x.IsActive == true).FirstOrDefault();
                        if (activeList != null)
                        {
                            activeList.IsActive = false;
                            con.Entry(activeList).State = System.Data.Entity.EntityState.Modified;
                            con.SaveChanges();
                        }
                        updateValue = true;
                    }
                    else if (status1 == 0)
                    {
                        updateValue = false;
                    }
                    else
                    {
                        isValid = false;
                    }
                }

                if (records != null && isValid)
                {
                    con.Entry(records).Property(propertyName).CurrentValue = updateValue;
                    con.SaveChanges();
                    status = true;                    
                }
                else
                {
                    message = "Error!";
                }
            }

            var response = new { value = updateValue, status = status, message = message };
            JObject o = JObject.FromObject(response);
            //return Content(o.ToString());
            return Json(new { value = updateValue, status = status, message = message }, JsonRequestBehavior.AllowGet);
        }


        public ActionResult Create()
        {
            FiscalYearRecordViewModel model = new FiscalYearRecordViewModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(FiscalYearRecordViewModel model)
        {
            var data = ent.Fiscal_Year_Record.ToList();
            if (data.Count > 0)
            {
                foreach (var item in data)
                {
                    item.IsActive = false;
                    ent.SaveChanges();
                }
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var Fiscal_Year_RecordEntity = new Fiscal_Year_Record()
                    {
                        Title = model.Title,
                        IsActive = true,
                        CreatedBy = model.CreatedBy,
                        CreatedDate = DateTime.Now,
                    };
                    ent.Fiscal_Year_Record.Add(Fiscal_Year_RecordEntity);
                    ent.SaveChanges();
                    TempData["Msg"] = "आर्थिक वर्ष सफलतापूर्वक सुरछित भयो। ";
                    return RedirectToAction("Index");
                }
                catch (Exception )
                {
                }
            }
            else
            {
                return View(model);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            FiscalYearRecordViewModel model = new FiscalYearRecordViewModel();
            var data = ent.Fiscal_Year_Record.Where(x => x.Fiscal_Year_Record_Id == id).SingleOrDefault();
            model.Fiscal_Year_Record_Id = data.Fiscal_Year_Record_Id;
            model.Title = data.Title;
            model.IsActive = data.IsActive??false;
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(FiscalYearRecordViewModel model)
        {

            if(model.IsActive==true)
            {
                var result = ent.Fiscal_Year_Record.Where(x => x.IsActive == true).ToList();
                if (result.Count() == 1)
                {
                    TempData["Msg"] = "पहिला सक्रिय अार्थिक वर्षलाई निष्क्रिय गर्नुहोस र यो अार्थिक वर्षलाई सक्रिय गर्नुहोस।";
                    return View(model);
                }
                else
                {
                    var data = ent.Fiscal_Year_Record.Where(x => x.Fiscal_Year_Record_Id == model.Fiscal_Year_Record_Id).SingleOrDefault();
                    data.Fiscal_Year_Record_Id = model.Fiscal_Year_Record_Id;
                    data.Title = model.Title;
                    data.IsActive = model.IsActive;
                    data.UpdatedBy = model.UpdatedBy;
                    data.UpdatedDate = DateTime.Now;
                    ent.SaveChanges();
                    TempData["Msg"] = "आर्थिक वर्ष सफलतापूर्वक सुरछित भयो। ";
                    return RedirectToAction("Index");
                }
            }
            else
            {
                var data = ent.Fiscal_Year_Record.Where(x => x.Fiscal_Year_Record_Id == model.Fiscal_Year_Record_Id).SingleOrDefault();
                data.Fiscal_Year_Record_Id = model.Fiscal_Year_Record_Id;
                data.Title = model.Title;
                data.IsActive = model.IsActive;
                ent.SaveChanges();
                TempData["Msg"] = "आर्थिक वर्ष सफलतापूर्वक सुरछित भयो। ";
                return RedirectToAction("Index");
            }
        }

    }
}

Planning/Areas/Admin/Views/FiscalYearRecord/Create.cshtml
@model Planning.Areas.Admin.Models.FiscalYearRecordViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="padding-md">
    @if (TempData["alreadyexist"] != null)
    {
        <div class="alert alert-info">
            <h5 style="text-align:center"><strong style="color:red;">@TempData["alreadyexist"]</strong></h5>
        </div>
    }

    <section style="background:#efefe9;">
        <div class="container">
            <div class="row">
                <div class="board">
                    <div class="tab-content">
                        <div class="tab-pane fade in active" id="fiscalYearRecord">
                            <h3 class="step_ttl">राख्नुहोस </h3>
                            @using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data", @class = "well", @id = "contact_form" }))
                            {
                                <fieldset>
                                    <div class="row">
                                        <div class="col-lg-4 col-md-6">
                                            <div class="form-group">
                                                <label>आर्थिक वर्ष</label>
                                                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="clearfix"></div>
                                    @*<div class="row">
                                        <div class="col-lg-4 col-md-6">
                                            <div class="form-group">
                                                <label>स्थिति</label>
                                                @Html.CheckBoxFor(model=>model.IsActive, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="clearfix"></div>*@
                                    <p>&nbsp;</p>
                                    <div class="form-group">
                                        <label class="col-lg-3  col-md-4 control-label"></label>
                                        <div class="col-lg-7 col-md-7">
                                            <button type="submit" class="btn btn-success">सुरक्षित गर्नुहोस </button>
                                            @Html.ActionLink("मुख्य मेनु", "Index", null, new { @class = "btn btn-info" })
                                        </div>
                                    </div>
                                </fieldset>
                            }
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
    </section>

</div>

Planning/Areas/Admin/Views/FiscalYearRecord/Edit.cshtml
@model Planning.Areas.Admin.Models.FiscalYearRecordViewModel
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="padding-md">

    @if (TempData["Msg"] != null)
    {
        <script>alert("@TempData["Msg"]");</script>
    }

    <section style="background:#efefe9;">
        <div class="container">
            <div class="row">
                <div class="board">
                    <div class="tab-content">
                        <div class="tab-pane fade in active" id="fiscalYearRecord">
                            <h3 class="step_ttl">राख्नुहोस </h3>
                            @using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data", @class = "well", @id = "contact_form" }))
                            {
                                @Html.HiddenFor(model=>model.Fiscal_Year_Record_Id)
                                <fieldset>
                                    <div class="row">
                                        <div class="col-lg-4 col-md-6">
                                            <div class="form-group">
                                                <label>आर्थिक वर्ष</label>
                                                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="clearfix"></div>
                                    <div class="row">
                                        <div class="col-lg-4 col-md-6">
                                            <div class="form-group">
                                                <label>स्थिति</label>
                                                @Html.CheckBoxFor(model => model.IsActive, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="clearfix"></div>
                                    <p>&nbsp;</p>
                                    <div class="form-group">
                                        <label class="col-lg-3  col-md-4 control-label"></label>
                                        <div class="col-lg-7 col-md-7">
                                            <button type="submit" class="btn btn-success">सुरक्षित गर्नुहोस </button>
                                            @Html.ActionLink("मुख्य मेनु", "Index", null, new { @class = "btn btn-info" })
                                        </div>
                                    </div>
                                </fieldset>
                            }
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

Planning/Areas/Admin/Views/FiscalYearRecord/Index.cshtml
@model List<Planning.Areas.Admin.Models.FiscalYearRecordViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    //int i = 1;
    WebGrid grid = new WebGrid(Model, rowsPerPage: 10);
}
<style>
    .w100 {
        width: 100px;
    }

    .margin10 {
        margin-left: 10px;
    }

    .btn {
        margin-left: 5px;
    }
    .cheakBoxbtn{
        margin-left: 15px;
    }

    .table input, select {
        height: 25px !important;
        width: inherit !important;
        border: 0;
        margin: 0;
        padding: 0;
        font: inherit;
        color: inherit;
    }
</style>
<div class="padding-md">

    @if (TempData["Msg"] != null)
    {
        <script>alert("@TempData["Msg"]");</script>
    }

    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="panel panel-default">
                <div class="header-list" style="text-align: center">
                    <h2> आर्थिक वर्ष</h2>
                </div>
                <div class="panel-heading">
                    @Html.ActionLink("नयाँ राख्नुहोस्", "Create", null, new { @class = "btn btn-success btn_add btn-xs" })
                </div>
                <div class="table">
                    @grid.GetHtml(
                    tableStyle: "table table-responsive table-striped table-bordered",
                    columns: grid.Columns(

                        grid.Column(header: "आर्थिक वर्ष", format:@<text><div class="edit" data-id="@item.Fiscal_Year_Record_Id" data-propertyname="Title">@item.Title</div></text>),
                        grid.Column(header: "स्थिति", format:@<text><div class="editSelect" data-id="@item.Fiscal_Year_Record_Id" data-propertyname="IsActive">
                         @if(item.IsActive){
                             @*<strong style="color:green;">सक्रिय</strong>*@
                            <span class="label label-success"><i class="fa fa-check-square-o"></i></span>
                         }
                         else
                         {
                            <span class="label label-danger label-mini"><i class="fa fa-star"></i></span>
                         }
                    </div></text>)
                        )
                   )
                </div>


                @*<table class="table table-bordered table-condensed table-hover table-striped" id="example">
                        <thead>
                            <tr class="success">
                                <th>क्र.स.</th>
                                <th>आर्थिक वर्ष</th>
                                <th>स्थिति</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.FiscalYearRecordViewModelList)
                            {
                                <tr>
                                    <th>@Planning.Utility.NepaliEnglishNumber.English_Nepali(i.ToString())</th>
                                    <td>@Html.DisplayFor(modelItem => item.Title)</td>
                                    <td>@Html.DisplayFor(modelItem => item.IsActive)</td>
                                    <td>
                                        <a class="btn btn-success btn-sm" title="Edit" href="@Url.Action("Edit", "FiscalYearRecord", new { id = item.Fiscal_Year_Record_Id })"><i class="fa fa-edit"></i> सच्याउनुहोस्</a>
                                    </td>
                                </tr>
                                i++;
                            }
                        </tbody>
                    </table>*@
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script src="~/Scripts/jeditable.js"></script>
    <script src="~/Scripts/jquery.jeditable.checkbox.js"></script>

    <script>
        $(document).ready(function () {
            var oldValue = '';
            $('.edit').editable('/FiscalYearRecord/EditTableData', {
                cssclass: 'custom-class',
                tooltip: 'click to edit me...',
                width: 'none',
                height: 'none',
                cancel: '<button class="btn btn-danger btn-sm">Cancel</button>',
                submit: '<button class="btn btn-success btn-sm">Save</button>',
                cancelcssclass: 'btn btn-danger',
                submitcssclass: 'btn btn-success',
                onsubmit: function (settings, original) {
                    oldValue = original.revert;
                },
                submitdata: function () {
                    return {
                        id: $(this).data('id'),
                        PropertyName: $(this).data('propertyname')
                    }
                },
                callback: function (value, settings) {
                    var jsonData = $.parseJSON(value);
                    if (jsonData.status) {
                        $(this).text(jsonData.value);
                    }
                    else {
                        $(this).text(oldValue);
                    }
                }
            });

            $('.editSelect').editable('/FiscalYearRecord/EditTableData', {
                cssclass: 'jeditForm',
                tooltip: 'click to edit me...',
                width: 'none',
                height: 'none',
                type: 'checkbox',
                submit: '<button class="btn btn-success btn-sm cheakBoxbtn">Save</button>',
                onsubmit: function (settings, original) {
                    oldValue = original.revert;
                },
                submitdata: function () {
                    return {
                        id: $(this).data('id'),
                        PropertyName: $(this).data('propertyname')
                    }
                },
                callback: function (value, settings) {
                    var jsonData = $.parseJSON(value);
                    if (jsonData.status) {
                        $(this).text(" ");
                    }
                    else {
                        $(this).text(" ");
                    }
                    location.reload();
                }
            });


        });
    </script>

}