Planning/Areas/Admin/Models/PlanningDocumentsViewModel/PlanningDocumentsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Planning.Areas.Admin.Models.PlanningDocumentsViewModel
{
    public class PlanningDocumentsViewModel
    {
        public int Planning_Documents_Id { get; set; }
        public Nullable<int> Planning_Samjhauta_Id { get; set; }
        public string Fiscal_Year { get; set; }
        public string Project_Name { get; set; }
        public string Upabhokta_Gathan { get; set; }
        public string Nirnaya { get; set; }
        public string Samjhauta { get; set; }
        public string Anuman { get; set; }
        public string Mapan { get; set; }
        public string Pramanikaran { get; set; }
        public string Karya_Sampanna { get; set; }
        public string Bhuktani_Nibedan { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }

        public List<PlanningDocumentsViewModel> PlanningDocumentsViewModelList { get; set; }
    }
}

Planning/Areas/Admin/Models/PlanningEntryViewModel/PlanningEntryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Planning.Areas.Admin.Models.PlanningEntryViewModel
{
    public class PlanningEntryViewModel
    {
        //For Planning_Entry
        public int Planning_Entry_Id { get; set; }
        public string FiscalYear { get; set; }
        public string Planning_Name { get; set; }
        public string Planning_Start_Date { get; set; }
        public string Planning_End_Date { get; set; }
        public string Work_Details { get; set; }
        public string Amount_Estimate { get; set; }
        public Nullable<int> Work_Type { get; set; }
        public Nullable<int> Ward_No { get; set; }
        public Nullable<int> Work_Area { get; set; }
        public Nullable<int> Budget_Source_Id { get; set; }
        public string Planning_Type { get; set; }
        public string UpaBhoktaSamiti_HeadName { get; set; }
        public string Contractor_Name { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        //New Added Field in DataBase
        public Nullable<System.DateTime> Planning_Completed_Date { get; set; }
        public string Total_Use_Amount { get; set; }

        //For Planning_Entry_Anudan
        public int Planning_Entry_Anudan_Id { get; set; }
        public string Nagarpalika_Amt { get; set; }
        public string UpaBhoktaSamiti_Amt { get; set; }
        public string Other_Amt { get; set; }
        public string JanaSahaBhagita_Amt { get; set; }

        //For Planning_Entry_Kista_Detail
        public int Planning_Entry_Kista_Detail_Id { get; set; }
        public string Kista_Kram { get; set; }
        public string Kista_Rakam { get; set; }
        public Nullable<System.DateTime> Payment_Date { get; set; }
        public string Peski_Bhuktani { get; set; }
        public string Sarta { get; set; }
        public string Remarks { get; set; }

        //others
        public string BudgetSource { get; set; }

        public List<PlanningEntryViewModel> PlanningEntryViewModelList { get; set; }

        public List<PlanningEntryViewModel> KistaFirstDetailsList { get; set; }
        public List<PlanningEntryViewModel> KistaSecondDetailsList { get; set; }
        public List<PlanningEntryViewModel> KistaThirdDetailsList { get; set; }
        public List<PlanningEntryViewModel> KistaLastDetailsList { get; set; }

        public List<PlanningEntryViewModel> OdaWiseViewModelList { get; set; }
        public List<PlanningEntryViewModel> NagarWiseViewModelList { get; set; }
        public List<PlanningEntryViewModel> AnuSuchiViewModelListByWard { get; set; }
        public List<PlanningEntryViewModel> AnuSuchiViewModelListByWorkArea { get; set; }

        //ORGANIZATION SETUP
        public int Organization_Setup_Id { get; set; }
        public string Organization_Name { get; set; }
        public string Organization_Type { get; set; }
        public string District_Name { get; set; }
        public string State_Country { get; set; }
        public string Image_Path { get; set; }
        public List<PlanningEntryViewModel> OrganizationSetupList { get; set; }


    }
}

Planning/Areas/Admin/Controllers/PlanningSamjhautaController/PlanningSamjhautaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Planning.Areas.Admin.Providers.PlanningSamjhautaProvider;
using Planning.Areas.Admin.Models.PlanningSamjhautaViewModel;
using Planning.Areas.Admin.Models.PlanningBhuktaniViewModel;
using Planning.Areas.Admin.Models.PlanningEntryViewModel;
using Planning.Areas.Admin.Models.PlanningDocumentsViewModel;
using Planning.Planning.Entities;
using System.IO;

using Microsoft.Office.Interop.Excel;
using System.Runtime.InteropServices;
using System.Web.UI;
using PagedList;
using Planning.Utility;
using Planning.Areas.Admin.Models;

namespace Planning.Areas.Admin.Controllers.PlanningSamjhautaController
{
    [Authorize]
    public class PlanningSamjhautaController : Controller
    {
        PLANNING_OCT_03Entities ent = new PLANNING_OCT_03Entities();
        PlanningSamjhautaProvider pro = new PlanningSamjhautaProvider();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult PlanningSamjhautaIndex(string currentFilterPlanning_Type, string currentFilterSamjhauta_Org_Name, bool? currentFilterSamjhauta_Acceptance, int? Currentward,
            string Planning_Type, string Samjhauta_Org_Name,int? Ward_No, bool? Samjhauta_Acceptance, int? page)
        {
            PlanningSamjhautaViewModel model = new PlanningSamjhautaViewModel();
            model.Current_Fiscal_Year_Record = Utility.CommonUtility.GetCurrentFiscalYearTitle();
            if (Planning_Type != null || Samjhauta_Org_Name != null || Samjhauta_Acceptance != null)
            {
                ViewBag.currentFilterPlanning_Type = Planning_Type;
                ViewBag.currentFilterSamjhauta_Org_Name = Samjhauta_Org_Name;
                ViewBag.currentFilterSamjhauta_Acceptance = Samjhauta_Acceptance;
                ViewBag.Ward_No = Ward_No;
                
                page = 1;
            }
            else if (page != null || currentFilterPlanning_Type != null || currentFilterSamjhauta_Org_Name != null || currentFilterSamjhauta_Acceptance != null || Currentward != null)
            {
                ViewBag.currentFilterPlanning_Type = currentFilterPlanning_Type;
                ViewBag.currentFilterSamjhauta_Org_Name = currentFilterSamjhauta_Org_Name;
                ViewBag.currentFilterSamjhauta_Acceptance = currentFilterSamjhauta_Acceptance;
                ViewBag.currentFilterWard = currentFilterSamjhauta_Acceptance;
                ViewBag.Currentward = Currentward;

                Planning_Type = currentFilterPlanning_Type;
                Samjhauta_Org_Name = currentFilterSamjhauta_Org_Name;
                Samjhauta_Acceptance = currentFilterSamjhauta_Acceptance;
            }
            else {
                Planning_Type = currentFilterPlanning_Type;
                Samjhauta_Org_Name = currentFilterSamjhauta_Org_Name;
                Samjhauta_Acceptance = currentFilterSamjhauta_Acceptance;
                Ward_No = Currentward;
            }
            // fatch Data From DataBase
            var year = model.Current_Fiscal_Year_Record;
            var List = pro.GetCurrentPlanningSamjhautaList(year);
            // Filter Data
            if (!string.IsNullOrEmpty(Planning_Type))
            {
                List = List.Where(x => x.Planning_Type.Contains(Planning_Type)).ToList();
            }
            if (!string.IsNullOrEmpty(Samjhauta_Org_Name))
            {
                List = List.Where(x => x.Samjhauta_Org_Name.Contains(Samjhauta_Org_Name)).ToList();
            }
            if (Ward_No!=null)
            {
                List = List.Where(x => x.Ward_No==Ward_No).ToList();
            }
            if (Samjhauta_Acceptance != null)
            {
                bool samjhauta_Acceptance = Samjhauta_Acceptance ?? false;
                List = List.Where(x => x.Samjhauta_Acceptance == samjhauta_Acceptance).ToList();
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(List.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult PlanningSamjhauta()
        {
            PlanningSamjhautaViewModel model = new PlanningSamjhautaViewModel();
            model.OrganizationSetupList = pro.GetOrganizationList();
            return View(model);
        }

        [HttpPost]
        public ActionResult PlanningSamjhauta(PlanningSamjhautaViewModel model)
        {
            var errors = ModelState.Where(x => x.Value.Errors.Count > 0).Select(x => new { x.Key, x.Value.Errors }).ToArray();

            model.FiscalYear = Utility.CommonUtility.GetCurrentFiscalYearTitle();
            if (!ModelState.IsValid)
            {
                model.OrganizationSetupList = pro.GetOrganizationList();
                TempData["Msg"] = "नगरपालिका कार्यालय र उपभोक्ता समिति बीचको सम्झौता सुरछित भएन! कृपया पु:न प्रयास गर्नुहोस। ";
                return View(model);
            }
            else
            {
                try
                {
                    //    model.Project_Start_Date = Convert.ToDateTime(Utility.CommonUtility.GetEnglishDateFromNepaliTest(model.NepaliProjStartDate));
                    //    model.Project_End_Date = Convert.ToDateTime(Utility.CommonUtility.GetEnglishDateFromNepaliTest(model.NepaliProjEndDate));
                    //    model.Samiti_Estd_Date = Convert.ToDateTime(Utility.CommonUtility.GetEnglishDateFromNepaliTest(model.NepaliSamitiEstdDate));
                    //    model.Municipality_Manjuri_Date = Convert.ToDateTime(Utility.CommonUtility.GetEnglishDateFromNepaliTest(model.NepaliMunicipalityManjuriDate));
                    if (model.NepaliProjStartDate != null)
                        model.Project_Start_Date = (Utility.CommonUtility.GetEnglishDateFromNepaliTest(model.NepaliProjStartDate)).ToString();
                    if (model.NepaliProjEndDate != null)
                        model.Project_End_Date =(Utility.CommonUtility.GetEnglishDateFromNepaliTest(model.NepaliProjEndDate)).ToString();
                    if (model.NepaliSamitiEstdDate != null)
                        model.Samiti_Estd_Date = Convert.ToDateTime(Utility.CommonUtility.GetEnglishDateFromNepaliTest(model.NepaliSamitiEstdDate));
                    if (model.NepaliMunicipalityManjuriDate != null)
                        model.Municipality_Manjuri_Date = (Utility.CommonUtility.GetEnglishDateFromNepaliTest(model.NepaliMunicipalityManjuriDate)).ToString();

                    model.Planning_Samjhauta_Id = pro.InsertPlanningSamjhauta(model);
                TempData["Msg"] = "नगरपालिका कार्यालय र उपभोक्ता समिति बीचको सम्झौता सफलतापूर्वक सुरछित भयो। ";

                }
                catch (Exception ex)
                {

                    //throw;
                }

                //return RedirectToAction("SamjhautaReport",new { planningSamjhautaId = model.Planning_Samjhauta_Id});
                //return RedirectToAction("SamjhautaReport");
                return RedirectToAction("SamjhautaCompleteReport", new { planningSamjhautaId = model.Planning_Samjhauta_Id });
            } 
        }

        public ActionResult AddMore()
        {
            PlanningSamjhautaViewModel model = new PlanningSamjhautaViewModel();
            return PartialView("_UpaBhoktaSamitiMembers", model);
        }

        public ActionResult PlanningSamjhautaEdit(int id)
        {
            PlanningSamjhautaViewModel model = new PlanningSamjhautaViewModel();
            model = pro.GetPlanningSamjhautaById(id).SingleOrDefault();

            try
            {
                //model.NepaliProjStartDate = Utility.CommonUtility.getNepaliDate(model.Project_Start_Date.Value.ToShortDateString());
                //model.NepaliProjEndDate = Utility.CommonUtility.getNepaliDate(model.Project_End_Date.Value.ToShortDateString());
                //model.NepaliSamitiEstdDate = Utility.CommonUtility.getNepaliDate(model.Samiti_Estd_Date.Value.ToShortDateString());
                //model.NepaliMunicipalityManjuriDate = Utility.CommonUtility.getNepaliDate(model.Municipality_Manjuri_Date.Value.ToShortDateString());
                if (model.Project_Start_Date != null)
                    model.NepaliProjStartDate = Utility.CommonUtility.getNepaliDate(model.Project_Start_Date);
                if (model.Project_End_Date != null)
                    model.NepaliProjEndDate = Utility.CommonUtility.getNepaliDate(model.Project_End_Date);
                if (model.Samiti_Estd_Date != null)
                    model.NepaliSamitiEstdDate = Utility.CommonUtility.getNepaliDate(model.Samiti_Estd_Date.Value.ToShortDateString());
                if (model.Municipality_Manjuri_Date != null)
                    model.NepaliMunicipalityManjuriDate = Utility.CommonUtility.getNepaliDate(model.Municipality_Manjuri_Date);

            }
            catch (Exception) 
            {

                //throw;
            }

            model.PlanningSamjhautaKistaFirstDetailsList = pro.GetKistaDetailListByPlanningSamjhautaId(id).Where(x => x.Kista_Kram == "पहिलो").ToList();
            model.PlanningSamjhautaKistaSecondDetailsList = pro.GetKistaDetailListByPlanningSamjhautaId(id).Where(x => x.Kista_Kram == "दोश्राे").ToList();
            model.PlanningSamjhautaKistaThirdDetailsList = pro.GetKistaDetailListByPlanningSamjhautaId(id).Where(x => x.Kista_Kram == "तेश्रो").ToList();

            model.KistaFirstDetailsList = pro.GetKistaDetailListByPlanningSamjhautaEntryId(id).Where(x => x.Kista_Kram == "पहिलो").ToList();
            model.KistaSecondDetailsList = pro.GetKistaDetailListByPlanningSamjhautaEntryId(id).Where(x => x.Kista_Kram == "दोश्राे").ToList();
            model.KistaThirdDetailsList = pro.GetKistaDetailListByPlanningSamjhautaEntryId(id).Where(x => x.Kista_Kram == "तेश्रो").ToList();

Planning/Areas/Admin/Views/PlanningSamjhauta/PlanningEntry.cshtml
@model Planning.Areas.Admin.Models.PlanningEntryViewModel.PlanningEntryViewModel


@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<script src="~/Scripts/jquery.maskedinput.js"></script>

<div class="padding-md">
    <section style="background:#efefe9;">
        <div class="container">
            <div class="row">
                <div class="board">
                    <div class="tab-content">
                        <div class="tab-pane fade in active" id="fiscalYearRecord">
                            <div class="main-content">

                                @using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))
                                {
                                    @Html.ValidationSummary()
                                    <div class="col-md-12">
                                        <div class="col-md-2"></div>
                                        <div class="col-md-8">
                                            @*<h3>योजना सम्झौता फारम</h3>*@
                                            <h3>योजना फारम</h3>
                                            <br /><br />
                                        </div>
                                        <div class="col-md-2"></div>
                                    </div>
                                    
                                    <div class="clearfix"></div>

                                    <div class="col-md-12">
                                        <div class="col-md-1"></div>
                                        <div class="col-md-1">आर्थिक वर्षः</div>
                                        <div class="col-md-6 form-group">@Html.TextBoxFor(model => model.FiscalYear, new{@class = "form-control",@required = "requierd",@*@placeholder = "___/___"*@  @placeholder = "उदाहरण(०७५/०७६)"})</div>
                                        <div class="clearfix"></div>
                                        <div class="col-md-1"></div>
                                        <div class="col-md-2">वडा स्तरिय/नगर स्तरिय</div>
                                        <div class="col-md-6 form-group">
                                            @Html.RadioButtonFor(model => model.Planning_Type, "O", new { @id = "oda", @class = "form-control-custom radio-custom" })
                                            <label for="oda" style="margin-left:20px;">वडा स्तरिय</label>
                                            &nbsp;&nbsp;&nbsp;&nbsp;
                                            @Html.RadioButtonFor(model => model.Planning_Type, "N", new { @id = "nagar", @class = "form-control-custom radio-custom" })
                                            <label for="nagar" style="margin-left:20px;">नगर स्तरिय</label>
                                        </div>
                                        <div class="clearfix"></div>
                                        <div class="col-md-1"></div>
                                        <div class="col-md-1">कार्यक्षेत्र  :</div>
                                        <div class="col-md-6 form-group">@Html.DropDownListFor(model => model.Work_Area, Planning.Utility.CommonUtility.GetWorkAreaList(), "---छान्नुहोस्---", new { @class = "form-control" })</div>
                                        <div class="clearfix"></div>
                                        <div class="clearfix"></div>
                                        <div class="col-md-1"></div>
                                        <div class="col-md-1">वडा नं. :</div>
                                        <div class="col-md-6 form-group">@Html.DropDownListFor(model=>model.Ward_No,Planning.Utility.CommonUtility.GetWardNoList(),"---छान्नुहोस्---" ,new { @class = "form-control" })</div>
                                        <div class="clearfix"></div>
                                        <div class="col-md-1"></div>
                                        <div class="col-md-1">वजेट श्रोत :</div>
                                        <div class="col-md-6 form-group">@Html.DropDownListFor(model => model.Budget_Source_Id, Planning.Utility.CommonUtility.GetBudgetSourceList(), "---छान्नुहोस्---", new { @class = "form-control" })</div>
                                        <div class="clearfix"></div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="col-md-4"><h5><strong> आयोजनाः सम्बनधी विवरण :</strong></h5></div>
                                        <div class="col-md-8"></div>
                                        <div class="clearfix"></div>
                                        <div class="col-md-1"></div>
                                        <div class="col-md-2">योजनाको नाम र स्थान :</div>
                                        <div class="col-md-6 form-group">@Html.TextBoxFor(model => model.Planning_Name, new { @class = "form-control" })</div>
                                        <div class="clearfix"></div>
                                        <div class="col-md-1"></div>
                                        <div class="col-md-2">योजना शुरु हुने मिति :</div>
                                        <div class="col-md-6 form-group">@Html.TextBoxFor(model => model.Planning_Start_Date, new { @class = "form-control", @placeholder = "____/__/__" })</div>
                                        <div class="clearfix"></div>
                                        <div class="col-md-1"></div>
                                        <div class="col-md-2">योजना सम्पन्न हुने मिति :</div>
                                        <div class="col-md-6 form-group">@Html.TextBoxFor(model => model.Planning_End_Date, new { @class = "form-control", @placeholder = "____/__/__" })</div>
                                        <div class="clearfix"></div>
                                        <div class="col-md-1"></div>
                                        <div class="col-md-2">कामको विवरण :</div>
                                        <div class="col-md-6 form-group">@Html.TextBoxFor(model => model.Work_Details, new { @class = "form-control" })</div>
                                        <div class="clearfix"></div>
                                        <div class="col-md-1"></div>
                                        <div class="col-md-2">लागत इष्टिमेट अङ्क रु :</div>
                                        <div class="col-md-6 form-group">@Html.TextBoxFor(model => model.Amount_Estimate, new { @class = "form-control" })</div>
                                        <div class="clearfix"></div>
                                        <div class="col-md-1"></div>
                                        <div class="col-md-2">कामको किसिम :</div>
                                        <div class="col-md-6 form-group">@Html.DropDownListFor(model => model.Work_Type, Planning.Utility.CommonUtility.GetWorkTypeList(), "---छान्नुहोस्---", new { @class = "form-control" })</div>
                                        <div class="clearfix"></div>
                                        <div class="col-md-1"></div>
                                        <div class="col-md-2"> अनुदान :</div>
                                        <div class="col-md-6"></div>
                                        <div class="clearfix"></div>
                                        <div class="col-md-1"></div>
                                        <div class="col-md-2">क. धनगढीमाई नगरपालिका</div>
                                        <div class="col-md-6 form-group">रु.@Html.TextBoxFor(model => model.Nagarpalika_Amt, new { @class = "form-control shrot" })</div>
                                        <div class="clearfix"></div>
                                        <div class="col-md-1"></div>
                                        <div class="col-md-2">ख. उ.स.</div>
                                        <div class="col-md-6 form-group">रु.@Html.TextBoxFor(model => model.UpaBhoktaSamiti_Amt, new { @class = "form-control shrot" })</div>
                                        <div class="clearfix"></div>
                                        <div class="col-md-1"></div>
                                        <div class="col-md-2">ग. अन्य</div>
                                        <div class="col-md-6 form-group">रु.@Html.TextBoxFor(model => model.Other_Amt, new { @class = "form-control shrot" })</div>
                                        <div class="clearfix"></div>
                                        <div class="col-md-1"></div>
                                        <div class="col-md-2">घ. जनसहभागीता</div>
                                        <div class="col-md-6 form-group">रु.@Html.TextBoxFor(model => model.JanaSahaBhagita_Amt, new { @class = "form-control shrot" })</div>
                                        <div class="clearfix"></div>
                                        <div class="col-md-1"></div>
                                        <div class="col-md-2">ङ. गेेर सरकारी संघ/संस्था</div>
                                        <div class="col-md-6 form-group"></div>
                                        <div class="clearfix"></div>
                                        <div class="col-md-2"></div>
                                        <div class="col-md-3">उपभोक्ता समितिको अध्यक्षको नाम र ठेगाना</div>
                                        <div class="col-md-6 form-group">@Html.TextBoxFor(model => model.UpaBhoktaSamiti_HeadName, new { @class = "form-control" })</div>
                                        <div class="clearfix"></div>
                                        <div class="col-md-2"></div>
                                        <div class="col-md-3">ठेकेदारको नाम र ठगाना</div>
                                        <div class="col-md-6 form-group">@Html.TextBoxFor(model => model.Contractor_Name, new { @class = "form-control" })</div>
                                        <div class="clearfix"></div>
                                    </div>
                                    <div class="clearfix"></div>
                                    <p></p><p></p>

                                    <div class="col-md-4"><h5 style="text-align:center;"><strong>ठेकेदारले न.पा. बाट प्रप्त गर्ने किस्ता विवरण</strong></h5></div>
                                    <div class="col-md-8"></div>
                                        <div class="clearfix"></div>

                                    //kista bibaran

                                    <div class="col-md-1">किस्ता क्रम </div>
                                    <div class="col-md-2">किस्ता रकम</div>
                                    <div class="col-md-2">मिति</div>
                                    <div class="col-md-2">पेश्की / भुक्तानी</div>
                                    <div class="col-md-2">शर्त</div>
                                    <div class="col-md-3">केेफियत</div>
                                    <div class="clearfix"></div>

                                    <div id="SourceFormgroup">
                                        <div class="form-group">
                                            <div class="col-lg-12 col-md-12 inputGroupContainer">
                                                <div class="row">
                                                        @Html.Partial("_FirstKista")
                                                        @Html.Partial("_SecondKista")
                                                        @Html.Partial("_ThirdKista")
                                                        @Html.Partial("_LastKista")
                                                </div>
                                            </div>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                    <div class="clearfix"></div>

                                    //

                                    <p></p><p></p>
                                        <div class="form-group">
                                            <label class="col-lg-3  col-md-4 control-label"></label>
                                            <div class="col-lg-7 col-md-7">
                                                <button type="submit" class="btn btn-success">सुरक्षित गर्नुहोस </button>
                                                <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("PlanningEntryIndex", "PlanningSamjhauta")'">मुख्य मेनु</button>
                                            </div>
                                        </div>
                                }
                            </div>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>


<script type="text/javascript">
    jQuery(function ($) {
        $("#Planning_Start_Date").mask("9999/99/99");
        $("#Planning_End_Date").mask("9999/99/99");
    });
</script>

Planning/Areas/Admin/Views/PlanningSamjhauta/_PlanningSamjhautaThirdKista.cshtml
@model Planning.Areas.Admin.Models.PlanningSamjhautaViewModel.PlanningSamjhautaViewModel
@using Planning.Helpers


<script src="~/js/nepali.datepicker.v2.2.min.js"></script>
<link href="~/css/bootstrap.min.css" rel="stylesheet" />
<link href="~/css/nepali.datepicker.v2.2.min.css" rel="stylesheet" />


@using (Html.BeginCollectionItem("PlanningSamjhautaKistaThirdDetailsList"))
{
    if (Model.Payment_Date != null)
    {
        var payment = Model.Payment_Date.Value.ToShortDateString();
        Model.NepaliPaymentDate = Planning.Utility.CommonUtility.getNepaliDate(payment);
    }
    @Html.HiddenFor(model => model.Kista_Kram, new { @class = "form-control", @Value = "तेश्रो" })
    <div class="col-md-1"></div>
    <div class="col-md-2">तेश्रो किस्ता</div>
    @*<div class="col-md-2">@Html.TextBoxFor(model => model.Payment_Date, new { @class = "form-control nepali-calendar", @id = "SamjhautaPayment_Date3", @placeholder = "____/__/__" })</div>*@
    <div class="col-md-2">@Html.TextBoxFor(model => model.NepaliPaymentDate, new { @class = "form-control nepali-calendar", @id = "SamjhautaPayment_Date3", @placeholder = "____/__/__" })</div>
    <div class="col-md-2">@Html.TextBoxFor(model => model.Kista_Rakam, new { @class = "form-control", @id = "Kista_Rakam3" })</div>
    <div class="col-md-2">@Html.TextBoxFor(model => model.Nirmarn_Samagri, new { @class = "form-control", @id = "Nirmarn_Samagri" })</div>
    <div class="col-md-3 form-group">@Html.TextAreaFor(model => model.Remarks, new { @class = "form-control", @id = "Nirmarn_Samagri" })</div>
    <div class="clearfix"></div>
}

<script type="text/javascript">
    $('#SamjhautaPayment_Date3').nepaliDatePicker({
        npdMonth: true,
        npdYear: true,
        npdYearCount: 10
    });
</script>

Planning/Areas/Admin/Views/PlanningSamjhauta/_UpaBhoktaSamitiMembers.cshtml
@model Planning.Areas.Admin.Models.PlanningSamjhautaViewModel.PlanningSamjhautaViewModel

@using Planning.Helpers


<script src="~/Scripts/jquery-1.10.2.min.js"></script>

@{ int i = 1;}

@using (Html.BeginCollectionItem("UpaBhoktaSamitiMemberList"))
{
    <div id="SamitiMembersFormgroup" class="form-group">
        <div class="col-md-3"></div>
                    <div class="col-md-6">@Html.EditorFor(model => model.Sadashya, new { htmlAttributes = new { @class = "form-control",@placeholder="सदस्य राख्नुहोस"} }) </div>
                    <div class="btn-delete col-md-1">
                        <div><a href='javascript:;' class="btn btn-danger btn-sm removesamitimember"><span class='fa fa-minus fa-1x'></span></a></div>
                    </div>
        <div class="clearfix"></div>
    </div>
}


<script>
    $(".removesamitimember").click(function () {
        $(this).parents("#SamitiMembersFormgroup").remove();
    });
</script>